name: dbmigrator_psql
description: PostgreSQL database migration library with file-based, versioned schema management supporting both upgrades and downgrades.
version: 0.1.2
repository: https://github.com/paschalisp/dbmigrator-psql-dart
homepage: https://github.com/paschalisp/dbmigrator-psql-dart
topics:
  - database
  - migration
  - versioning
  - postgresql


environment:
  sdk: ">=3.10.0 <4.0.0"


dependencies:
  crypto: ^3.0.7
  dbmigrator: ^0.1.2
  postgres: ^3.5.9

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
